// <auto-generated />
using System;
using EFMigracije.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230921091539_ante1")]
    partial class ante1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Prvi",
                            Section = "a",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Drugi",
                            Section = "b",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "Treci",
                            Section = "c",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "Cetvrti",
                            Section = "d",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Peti",
                            Section = "e",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "Sesti",
                            Section = "f",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "Sedmi",
                            Section = "g",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 8,
                            GradeName = "Osmi",
                            Section = "h",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2015, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 180m,
                            StudentName = "Ante",
                            Weight = 105f
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2002, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 170m,
                            StudentName = "Marija",
                            Weight = 56f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
